# Change these first
owner: ashengstd # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

sites:
  - name: Serv00
    url: https://ascka.serv00.net/
  - name: Edge
    url: https://config.ascka.qzz.io/ui/
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
  - name: Blog 
    url: https://blog.tomorrowisinyourhands.fun/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ascka.qzz.io
  baseUrl: /StatusPage
  themeUrl: https://ashengstd.github.io/StatusPage/catppuccin.css
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ascka Status
  introTitle: "**Ascka's Status**"
  introMessage: Welcome to Ascka's service status monitoring page, which displays the online status of all nodes and services in real-time.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
